# Generated by Django 2.2.4 on 2019-08-22 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weser', '0003_emergency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('posology', models.CharField(max_length=200)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weser.Entity')),
            ],
        ),
        migrations.RenameField(
            model_name='emergency',
            old_name='patient',
            new_name='assistent',
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('minpress', models.CharField(max_length=200)),
                ('maxpress', models.CharField(max_length=200)),
                ('mincir', models.CharField(max_length=200)),
                ('maxcir', models.CharField(max_length=200)),
                ('mintemp', models.CharField(max_length=200)),
                ('maxtemp', models.CharField(max_length=200)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weser.Entity')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weser.Cure')),
            ],
        ),
    ]
