# Generated by Django 2.2.4 on 2019-08-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weser', '0004_auto_20190822_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='patient',
            new_name='cure',
        ),
    ]
